### ISSUE TITLE
Deeper Gas Report

### ISSUE THREAD

**Issue by johnnyshankman** [bad-baby-bear-bots/ERC721B#4]
A user on twitter made an incredible breakdown of ERC721 vs ERC721A that goes a little deeper than just one transfer and I'd love to see that added to this repo so all of us can really get a deep understanding of the gas optimizations at every point down the road.

https://twitter.com/CryptoMuppa/status/1496137580999548943?s=20&t=DLkItWz-TJbiupHotWAkoA

![image](https://user-images.githubusercontent.com/6632701/160015673-9a0c70a1-eb22-4863-b495-591dc712c908.png)

**Comment by johnnyshankman** [comment]
The key here is that there's two sets of minting. Minting tokens 1-5, doing some transfers, then minting 6-10 and transferring those tokens around as well.

**Comment by cblanquera** [comment]
sure thing will add to the readme on my next push

**Comment by cblanquera** [comment]
it's now found in https://github.com/badbabybearbots/ERC721B#6-reports
